//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aleatorio
    {
        public int IdAleatorio { get; set; }
        public string Palavra { get; set; }
        public string Dica { get; set; }
    }
}
